version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: nest-totp-pg-container
    ports:
      - 8432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      TZ: 'America/Sao_Paulo'
